/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SessionIdRouteImport } from './routes/$sessionId'
import { Route as GameRouteRouteImport } from './routes/_game/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameLobbyRouteImport } from './routes/_game/lobby'
import { Route as GameGameRouteImport } from './routes/_game/game'
import { Route as UserIdSettingsRouteImport } from './routes/$userId.settings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRouteRoute = GameRouteRouteImport.update({
  id: '/_game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameLobbyRoute = GameLobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => GameRouteRoute,
} as any)
const GameGameRoute = GameGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => GameRouteRoute,
} as any)
const UserIdSettingsRoute = UserIdSettingsRouteImport.update({
  id: '/$userId/settings',
  path: '/$userId/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$sessionId': typeof SessionIdRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/$userId/settings': typeof UserIdSettingsRoute
  '/game': typeof GameGameRoute
  '/lobby': typeof GameLobbyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$sessionId': typeof SessionIdRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/$userId/settings': typeof UserIdSettingsRoute
  '/game': typeof GameGameRoute
  '/lobby': typeof GameLobbyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_game': typeof GameRouteRouteWithChildren
  '/$sessionId': typeof SessionIdRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/$userId/settings': typeof UserIdSettingsRoute
  '/_game/game': typeof GameGameRoute
  '/_game/lobby': typeof GameLobbyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$sessionId'
    | '/dashboard'
    | '/login'
    | '/$userId/settings'
    | '/game'
    | '/lobby'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$sessionId'
    | '/dashboard'
    | '/login'
    | '/$userId/settings'
    | '/game'
    | '/lobby'
  id:
    | '__root__'
    | '/'
    | '/_game'
    | '/$sessionId'
    | '/dashboard'
    | '/login'
    | '/$userId/settings'
    | '/_game/game'
    | '/_game/lobby'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRouteRoute: typeof GameRouteRouteWithChildren
  SessionIdRoute: typeof SessionIdRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  UserIdSettingsRoute: typeof UserIdSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$sessionId': {
      id: '/$sessionId'
      path: '/$sessionId'
      fullPath: '/$sessionId'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_game': {
      id: '/_game'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_game/lobby': {
      id: '/_game/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof GameLobbyRouteImport
      parentRoute: typeof GameRouteRoute
    }
    '/_game/game': {
      id: '/_game/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameGameRouteImport
      parentRoute: typeof GameRouteRoute
    }
    '/$userId/settings': {
      id: '/$userId/settings'
      path: '/$userId/settings'
      fullPath: '/$userId/settings'
      preLoaderRoute: typeof UserIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GameRouteRouteChildren {
  GameGameRoute: typeof GameGameRoute
  GameLobbyRoute: typeof GameLobbyRoute
}

const GameRouteRouteChildren: GameRouteRouteChildren = {
  GameGameRoute: GameGameRoute,
  GameLobbyRoute: GameLobbyRoute,
}

const GameRouteRouteWithChildren = GameRouteRoute._addFileChildren(
  GameRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRouteRoute: GameRouteRouteWithChildren,
  SessionIdRoute: SessionIdRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  UserIdSettingsRoute: UserIdSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
