/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Game_lobbyRouteImport } from './routes/game_lobby'
import { Route as GameRouteImport } from './routes/game'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SessionIdRouteImport } from './routes/$sessionId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIdSettingsRouteImport } from './routes/$userId.settings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Game_lobbyRoute = Game_lobbyRouteImport.update({
  id: '/game_lobby',
  path: '/game_lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdSettingsRoute = UserIdSettingsRouteImport.update({
  id: '/$userId/settings',
  path: '/$userId/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$sessionId': typeof SessionIdRoute
  '/dashboard': typeof DashboardRoute
  '/game': typeof GameRoute
  '/game_lobby': typeof Game_lobbyRoute
  '/login': typeof LoginRoute
  '/$userId/settings': typeof UserIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$sessionId': typeof SessionIdRoute
  '/dashboard': typeof DashboardRoute
  '/game': typeof GameRoute
  '/game_lobby': typeof Game_lobbyRoute
  '/login': typeof LoginRoute
  '/$userId/settings': typeof UserIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$sessionId': typeof SessionIdRoute
  '/dashboard': typeof DashboardRoute
  '/game': typeof GameRoute
  '/game_lobby': typeof Game_lobbyRoute
  '/login': typeof LoginRoute
  '/$userId/settings': typeof UserIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$sessionId'
    | '/dashboard'
    | '/game'
    | '/game_lobby'
    | '/login'
    | '/$userId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$sessionId'
    | '/dashboard'
    | '/game'
    | '/game_lobby'
    | '/login'
    | '/$userId/settings'
  id:
    | '__root__'
    | '/'
    | '/$sessionId'
    | '/dashboard'
    | '/game'
    | '/game_lobby'
    | '/login'
    | '/$userId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionIdRoute: typeof SessionIdRoute
  DashboardRoute: typeof DashboardRoute
  GameRoute: typeof GameRoute
  Game_lobbyRoute: typeof Game_lobbyRoute
  LoginRoute: typeof LoginRoute
  UserIdSettingsRoute: typeof UserIdSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game_lobby': {
      id: '/game_lobby'
      path: '/game_lobby'
      fullPath: '/game_lobby'
      preLoaderRoute: typeof Game_lobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$sessionId': {
      id: '/$sessionId'
      path: '/$sessionId'
      fullPath: '/$sessionId'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$userId/settings': {
      id: '/$userId/settings'
      path: '/$userId/settings'
      fullPath: '/$userId/settings'
      preLoaderRoute: typeof UserIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionIdRoute: SessionIdRoute,
  DashboardRoute: DashboardRoute,
  GameRoute: GameRoute,
  Game_lobbyRoute: Game_lobbyRoute,
  LoginRoute: LoginRoute,
  UserIdSettingsRoute: UserIdSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
