name: inboxkit-assignment

services:
  postgres:
    image: postgres
    container_name: inboxkit-assignment-postgres
    environment:
      POSTGRES_DB: inboxkit-assignment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "6891:5432"
    volumes:
      - inboxkit-assignment_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: inboxkit-assignment-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  inboxkit-assignment_postgres_data:
